### ISSUE TITLE
FreeMCBoot license

### ISSUE THREAD

**Issue by AKuHAK** [TnA-Plastic/FreeMcBoot#8]
@sp193 what was the license for FMCB 1.9? Is it the same as the 1.8b license? I didn't find any mention of a license on the official [FCMB 1.9 site](https://sites.google.com/view/ysai187/home/projects/fmcbfhdb) or inside downloadable packages.

Cause it looks like FMCB 1.9 is breaking the following license rule:
https://github.com/TnA-Plastic/FreeMcBoot/blob/2e4eef9a1ec5612cde1121d185996fd08fecb930/LICENSE.txt#L50

Or maybe @jimmikaelkael changed the license for the 1.9 release?

**Comment by sp193** [comment]
It should have been the same as 1.8b. 10 years ago, I did not care much about licensing.
1.8b and 1.8c were closed source, so 1.9 was also closed-source. 1.9 was my idea because I wanted to add support the console designs I loved and to get FMCB to use the right way of initializing the console. I did not interact much with the original authors.

It is not possible for me to prepare the source code archives for public release and neither would I want to run the project anymore. So if anyone finds a problem with the old packages, I will take them down to align with the license.

**Comment by AKuHAK** [comment]
@sp193 it was not about removing something but more about the fact that, maybe, you had another license, not as strict as 1.8b. For example, current FMCB cannot be used as a part of sold hardware, cause it breaks the license, I asked just in hope that 1.9 was different in that case.

**Comment by sp193** [comment]
Maybe there is something I am not understanding. Even if I did not actually follow the licensing terms properly, wouldn't the issue solely lie with my work? I mean, if you bundled FMCB with something else, I do not suppose your bundle would be considered a derivative work of FMCB because you did not create a new version of this FMCB program?
